cleaned up the dockerfile, updated the jenkinsfile to my current build, cleaned up the local builds in make, and updated the readme some.

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,17 +1,19 @@
 pipeline {
-    // The host will need to have docker installed to build the images
     agent any
     environment {
         GIT_URL='https://github.com/jtom38/docker-ansible.git'
         GIT_BRANCH='main'
-        DOCKER_TAG='2.9.11'
-        DOCKER_HUB_REPO='jtom38/ansible'
+        DOCKER_IMAGE='jtom38/ansible'
+        DOCKER_TAG_1='2.9.11'
+        DOCKER_TAG_2='2.10.3'
+        TF_VER='0.13.5'
     }
 
     stages {
         stage('Pull-Source') {
             steps {
                 sh '''#!/bin/bash
+                rm -r ./workspace || echo "directory was not found and thats okay"
                 git clone ${GIT_URL} workspace
                 cd ./workspace
                 git checkout ${GIT_BRANCH}
@@ -21,17 +23,108 @@ pipeline {
         stage('Build-Image-2.9') {
             steps {
                 sh '''#!/bin/bash
-                #docker build -t ansible:2.9 ./workspace/.devcontainer/2.9.11/
-                make build-image-2.9
+                cd ./workspace
+                docker build -t jtom38/ansible:2.9.11 . --build-arg ANSIBLE_VER=2.9.11 --build-arg TF_VER=${TF_VER}
                 '''
             }
         }
-        stage('Build-Image-2.10.2') {
+        stage('Test-Image-2.9'){
+            // Spawn the image and run the version commands to make sure the applications installed.
+            agent{
+                docker {
+                    image 'jtom38/ansible:2.9.11'
+                    args '-u 0:0'
+                }
+            }
             steps {
                 sh '''#!/bin/bash
-                #docker build -t ansible:2.10.2 ./workspace/.devcontainer/2.10.2/
-                make build-image-2.10
+                ansible --version
+                terraform --version
+                molecule --version
+                docker --version
                 '''
+            }
+        }
+        stage('Push-Image-2.9-Hub'){
+            steps{
+                withCredentials([string(credentialsId: 'docker-password-secret', variable: 'DOCKERPASS')]) {
+                    sh '''#!/bin/bash
+                    echo ${DOCKERPASS} | docker login -u jtom38 --password-stdin
+                    docker push jtom38/ansible:2.9.11
+                    '''
+                }
+            }
+        }
+        stage('Build-Image-2.10') {
+            steps {
+                sh '''#!/bin/bash
+                cd ./workspace
+                docker build -t jtom38/ansible:2.10.3 . --build-arg ANSIBLE_VER=2.10.3 --build-arg TF_VER=${TF_VER}
+                docker logout
+                '''
+            }
+        }
+        stage('Test-Image-2.10') {
+            agent {
+                docker {
+                    image 'jtom38/ansible:2.10.3'
+                    args '-u 0:0'
+                }
+            }
+            steps {
+                sh '''#!/bin/bash
+                ansible --version
+                terraform --version
+                molecule --version
+                docker --version
+                '''
+            }
+        }
+        stage('Push-Image-2.10-Hub'){
+            steps{
+                withCredentials([string(credentialsId: 'docker-password-secret', variable: 'DOCKERPASS')]) {
+                    sh '''#!/bin/bash
+                    echo ${DOCKERPASS} | docker login -u jtom38 --password-stdin
+                    docker push jtom38/ansible:2.10.3
+                    docker logout
+                    '''
+                }
+            }
+        }
+        stage('Build-Image-Latest') {
+            steps {
+                sh '''#!/bin/bash
+                cd ./workspace
+                docker build -t jtom38/ansible:latest . --build-arg ANSIBLE_VER=2.10.3 --build-arg TF_VER=${TF_VER}
+                docker logout
+                '''
+            }
+        }
+        stage('Test-Image-Latest') {
+            agent {
+                docker {
+                    image 'jtom38/ansible:latest'
+                    args '-u 0:0'
+                }
+            }
+            steps {
+                sh '''#!/bin/bash
+                ansible --version
+                terraform --version
+                molecule --version
+                docker --version
+                '''
+            }
+        }
+        stage('Push-Image-Latest-Hub'){
+            steps{
+                withCredentials([string(credentialsId: 'docker-password-secret', variable: 'DOCKERPASS')]) {
+                    sh '''#!/bin/bash
+                    echo ${DOCKERPASS} | docker login -u jtom38 --password-stdin
+                    docker push jtom38/ansible:latest
+                    docker logout
+                    '''
+                }
             }
         }
     }
